frontend:
  image: xueqiut/frontend
  tag: 424efe3
  autoscaling:
    averageUtilization: 90
backend:
  image: xueqiut/backend
  tag: 424efe3
  autoscaling:
    averageUtilization: 90
database:
  enabled: true
  uri: pg-service
  username: postgres
  password: postgres
