frontend:
  image: xueqiut/frontend
  tag: c2b2985
  autoscaling:
    averageUtilization: 90
backend:
  image: xueqiut/backend
  tag: c2b2985
  autoscaling:
    averageUtilization: 90
database:
  enabled: true
  uri: pg-service
  username: postgres
  password: postgres
